services:
  - type: web
    name: public_space
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn public_space.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "django-insecure-0+w1teh(-+$!ur8b&xl9xaxu$-*%tzpegjzq0$(fl$mjoi0ij1"
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "two-public-space.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SETTINGS_MODULE
        value: "public_space.settings"
      - key: DATABASE_URL
        value: "sqlite://:memory:"  # or your PostgreSQL URL
    autoDeploy: true
