services:
  - type: web
    name: public_space
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn public_space.wsgi:application"
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "django-insecure-0+w1teh(-+$!ur8b&xl9xaxu$-*%tzpegjzq0$(fl$mjoi0ij1"
      - key: DJANGO_DEBUG
        value: "false"
      
      - key: DJANGO_SETTINGS_MODULE
        value: "public_space.settings"
      - key: DJANGO_ALLOWED_HOSTS
        value: "two-public-space.onrender.com,localhost,127.0.0.1" 
    autoDeploy: true

databases:
  - name: default
    type: postgres
    plan: free
