services:
  - type: web
    name: public_space
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn public_space.wsgi:application"
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "your-secret-key"
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: ["public-space-kqdf.onrender.com,localhost,127.0.0.1","two-public-space.onrender.com,localhost,127.0.0.1"]
      - key: DATABASE_URL
        value: "postgres://username:password@hostname:port/database"
      - key: DJANGO_SETTINGS_MODULE
        value: "public_space.settings"
    autoDeploy: true
