services:
  - type: web
    name: public-space
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn public_spcace.wsgi:application"
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "django-insecure-0+w1teh(-+$!ur8b&xl9xaxu$-*%tzpegjzq0$(fl$mjoi0ij1"
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "public_space.onrender.com"

      - key: DATABASE_URL
        value: "postgres://username:password@hostname:port/database"
      - key: DJANGO_SETTINGS_MODULE
        value: "public_space.settings.production"
    autoDeploy: true

databases:
  - name: default
    type: postgres
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgres://username:password@hostname:port/database"
