# Generated by Django 5.1.5 on 2025-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_alter_follow_created_at_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='space.profile'),
        ),
    ]
