# Generated by Django 5.1.5 on 2025-04-14 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0018_tweet_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_limit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='space.userprofile'),
        ),
    ]
